### ISSUE TITLE
Change Type of Ratings

### ISSUE THREAD

**Issue by haip50** [Mike-Aniki/Aniki-ReMake#10]
Hi Mike,

Is there a way to change the star rating to user score? Mine seems to pull from critic score and community score and they don't line up with my desktop version.

Really really love the theme. Thank you!

**Comment by Mike-Aniki** [comment]
Sorry for the confusion, my fault. It's a translation error from French to English, because for me “user score” meant “the score given by users (what Playnite calls the community score”) and not the personal score given by the user.
I made a literal translation from French to English, and "user" might not be appropriate here. I will change this to "community score" in the next updates.

As for adding the personal score , I'll look at how I can integrate it as an option in the next update

**Comment by haip50** [comment]
That makes sense. Thank you for the response!

**Comment by haip50** [comment]
I just wanted to say thanks for the update. It looks amazing. I so love this theme.
