### ISSUE TITLE
Filter logos at the bottom of the screen.

### ISSUE THREAD

**Issue by Myardax** [Mike-Aniki/Aniki-ReMake#3]
This is really not an issue but some of the filter icons are quite oversized compared to the others and just looks awkward to me. Is there any way of shrinking these so they all are about the same size?

**Comment by Mike-Aniki** [comment]
Sorry for the delay in replying, yes the images are not all the same size, that's why some logos are bigger than others. the reason is that I didn't make them, they were downloaded from logo packs.

To make it cleaner, you have to edit the images and put them all at the same size, and given the number of images this requires a lot of work and time so I wouldn't do it personally, but you can very well edit the images you use and put them all at the same size with an image editor, that's what I did for the filters I use, if you look at my screen the icons are all at the same size.
