### ISSUE TITLE
Theme on TV is a bit misaligned

### ISSUE THREAD

**Issue by LAG87** [Mike-Aniki/Aniki-ReMake#6]
First of all, great work on this theme. 
I believe it is the most updated theme and its integration with other plugins is the best among all other fullscreen themes. 

With that said, I have a small issue when using it on my 43" TV (resolution of 4096 x 2160). 
For some reason, on the TV, the bottom bar (where the filters are) on the main page is a bit misaligned with the rest of the UI elements. 
Also, when going to the details of a game, again the bottom bar, the top bar and also the main area are all misaligned with each other.

To better illustrate the issue I took some screenshots, of both the main page and the details page:
![tv_1](https://github.com/user-attachments/assets/577d7c86-dc7a-4387-9128-264abee3e5da)
![tv_2](https://github.com/user-attachments/assets/f51bd39d-ed2c-4e86-9209-e663f9fa0969)

I though I had something misconfigured, but I also tested the theme on my 23.8" monitor (resolution of 1920x1080) and everything is being displayed correctly:
![monitor_1](https://github.com/user-attachments/assets/1a950c22-694d-45df-aea0-5508ee2a0ad4)
![monitor_2](https://github.com/user-attachments/assets/9f925b52-5db1-4940-92a2-d6535e1f9792)

So, my question is whether if there is something I may have misconfigured or missed so that on the TV everything can be displayed correctly and all aligned. Or if even the theme is not being supported for TVs (or 4K resolutions).

Thank you!

**Comment by josehb96** [comment]
Try changing to 16:10 instead of 16:9 in the fullscreen mode settings. That might work.

**Comment by LAG87** [comment]
I tried it but unfortunately it did not solve the issue 😔

**Comment by Mike-Aniki** [comment]
_**Thank you for your feedback and kind words about the theme!**_

The issue you're experiencing is related to the 4096 x 2160 resolution. On TVs, the standard 4K resolution is 3840 x 2160, also known as Ultra HD. When connecting a PC to a 4K Ultra HD TV, the PC identifies the maximum possible resolution of 4096 x 2160, but you may notice that Windows recommends using 3840 x 2160.

### A quick overview of these two resolutions :

**4096 x 2160 (Cinema 4K or DCI 4K) :**

- Primarily used in cinema and some professional applications.
- This format has a slightly wider aspect ratio, about 17:9.

**3840 x 2160 (Ultra HD or UHD) :**

- The consumer 4K standard used by TVs.
- A 16:9 aspect ratio designed to match the proportions of television screens.

When your PC detects 4096 x 2160 as the maximum resolution, it can create misalignments in the user interface because the theme is designed for 16:9. This can also lead to similar issues in games where the resolution cannot be changed (e.g., when playing in borderless windowed mode). In such cases, the game runs at 4096 x 2160, and you may see black bars on the sides.

### Solution: Remove the 4096 x 2160 resolution with CRU

To resolve this, you can use a small utility called Custom Resolution Utility (CRU) to remove support for the 4096 x 2160 resolution. 

- Download CRU from [this official link](https://www.monitortests.com/download/cru/cru-1.5.2.zip).
- Here you'll find a step-by-step procedure : [Tuto CRU](https://www.monitortests.com/blog/guide-how-to-remove-4096x2160/)

**I'm still writing you the procedure :**

- Open CRU and select your connected screen (it will be marked as "active").
- In the Extension Blocks section, click Edit.
- Find all entries corresponding to 4096 x 2160 and delete them one by one.
- Click OK to save the changes, then close CRU.
- Run the included restart64.exe application to restart the graphics driver.

Let me know if this resolves your issue or if you encounter any other problems !

**Comment by LAG87** [comment]
Thank you very much for the detailed answer!

And not only a great answer but also the solution to my issue. 
I did what you mentioned, and used CRU to remove 4096 x 2160 resolution from my system, and now everything is working perfectly on my TV.

And thank you also for the enlightenment, regarding the differences between the different 4K resolutions (Cinema 4K and Ultra HD). 
I wasn't aware of those differences, but they make sense.

And I guess with this solution this will not only solve the misalignment issue when using your theme but also with games when playing in borderless windowed mode, so that's a good bonus.

Anyway, the issue is now solved, so I will close this ticket.

Once again, thank you very much for your time and help. 
Keep up the good work!
